### ISSUE TITLE
Getting started should tell how to install generator

### ISSUE THREAD

**Issue by winkler1** [ericclemmons/genesis-skeleton#120]
The instructions go from "npm install -g yo bower grunt-cli" to "yo genesis"

... skipped a step, which will frustrate newcomers.

**Comment by megalithic** [comment]
... and what steps are missing? to help un-frustrate newcomers, perhaps list the missing steps?

**Comment by winkler1** [comment]
The http://genesis-skeleton.com/ page says-

```
The NPM dependencies can easily be installed at once via:
npm install -g yo bower grunt-cli
INSTALLATION
From within any new or existing project directory:
yo genesis
```

Should add **generator-genesis** to the npm install command line.

**Comment by ericclemmons** [comment]
Ah, it's because the `gh-pages` branch is out of date from `master`.

I reverted 1f09bc478efa5fd34e70b0e7b2a2935ae5a30a2b and http://genesis-skeleton.com/ uses the `master` version now.

Also, heads up, this project is moving to https://github.com/genesis/ and the generator is being updated to use Gulp :)
