### ISSUE TITLE
http://localhost:3001/#/guide is a 404 page

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#54]
Seems to be an error, unless this is to demo the 404 page functionality.

**Comment by kwhitley** [comment]
Yeah there's nothing behind `/guide` at the moment - we were testing 404's and 500's today (in #48)...  you're catching it right before we finalize v 1.0 :baby_symbol: 

Thanks for helping us tear through it!  Need more eyes....

**Comment by facultymatt** [comment]
Nice, yes this seems to be solved by PR 48 as you mentioned although I haven't tested the pull request myself. 

Might I suggest an alternate implementation... It works in theory but not sure its technically possible (I was actually trying to make this happen when I stumbled across a stack overflow conversation with a link here!) because of relative paths and also I'm not that familiar with Angularjs
- If a user visits a url such as `/guide/step1`, instead of redirecting to `/#/guide/step1`, using express the server would actually serve the public/index.html file. This can be done a number of ways, such as expressjs's sendFile() function. 
- This causes the Angular app to load, (although @note that relative paths might be incorrect since they will be relative to `/guide/` and not '/'. ) 
- When the angular app loads, the angular router detects the path and runs the appropriate functions to render the page. 
- If a browser doesn't support html5 pushstate, the angular router adjusts the url to be a hash. Else, if the browser does support pushState everything looks great! 

The main advantage I see here are is
-  the server / app / public setup supports pushstate when possible. Which looks prettier and is much more natural for users. (Not to mention supported by all but legacy and IE)  

The main disadvantage I see is:
- functionality is dependent on AngularJS which makes switching to another MVC framework a bit more complex. 
- relative paths may potentially need to be absolute instead (not sure this can be done, maybe with js variables?)

It would be great to hear you opinion on this approach.
-Matt

**Comment by ericclemmons** [comment]
@facultymatt Funny thing is, probably a day or two ago this was the approach we were using: defaulting to HTML5 pushstate and having all routes render the app.  AngularJS caught this easily via `$router.otherwise(...)`.  Sure enough, working routes rendered as normal, which meant that the URLs could have some permanence.

Since we're using Modernizr, it would be possible to confirm pushstate support and enable it within the app.  The one annoyance with Angular so far is that generating routes via `ng-href` doesn't easily support the toggling of `#/`.

I'm going to keep this open while we merge down the other issues & come back to it...

Thanks!

**Comment by facultymatt** [comment]
Ahh yes, that would be another major disadvantage I didn't think about... adding the #/ to links. I played around with it this morning and while Angular documentation suggests this should be easier... I wasn't able to get the links working, using one pattern, for both html5 and hashbangs.

I'll keep working on this one and keep you all posted. Thanks!

**Comment by facultymatt** [comment]
Idea! What if we use modernizer to detect pushState, if supported

```
Set a ng-href template variables, such as {hash} to be '"" 
Set $location.html5Mode(true);
```

If not supported, 

```
Set {hash} to be "#"
Set html5Mode = false
```

This would require that developers use ng-href (instead of href) and always include the hash var `ng-ref="{hash}/guide"` which adds a little overhead, while minimal. 

It would also require a bit of config and different execution should the developer want to use another MVC library. Maybe there could be a config setting (in package or grunt?) that if set to true, would look for an additional file, something like "html5support.js" where the user could write the js needed for their particular framework. Of course Genesis would come already with the Angular js. 

Thoughts?

**Comment by ericclemmons** [comment]
I'm not opposed to using `ng-href` and, what would have to be, a `$rootScope` variable.  Although, I feel that there is a root issue to be resolved, in which angular doesn't, from what I've seen, support named routes.  Otherwise, we could have much simpler generation via something like:

``` js
// app.js
$router.when('/home', {
    controller: 'app.controllers.home',
    template: 'home.html',
    name: 'app.routes.home'
});
```

``` html
<!-- nav.html -->
<a ng-route="app.routes.home'>Go Home, Forrest!</a>
```

`ng-route` (or some equivalent) would be able to generate a defined route with default params and necessary hash dynamically.

Would a filter at least work?  That looks kind of ugly, IMO, but it wouldn't be the craziest thing we've done...

``` html
<!-- nav.html -->
<a ng-href="{{ '/home' | html5 }}">Go HTML5!</a>
```

**Comment by facultymatt** [comment]
Ok, I implemented the above in my fork and it works pretty well. @see https://github.com/facultymatt/genesis-skeleton/commit/707609d408d235083a8093abe311009610e57ee4 There is still an issue where the server redirects pages to the hashed counterpart, and then Angular removes the hash if we are using pushstate. This is a bit odd... ideally, the server would always serve up the index file, regardless of the url, and then Angular would add the hash if needed (instead of remove it)

**Comment by ericclemmons** [comment]
So we could remove the redirect to the hashed counterpart (let Angular do that, if HTML5 history isn't supported), but instead just render the home page for _all_ routes not explicitly defined on the server.

Basically, what your last sentence said :)

**Comment by facultymatt** [comment]
In theory, but on my first attempt I was getting redirect loops ;) will work on it more after lunch.

**Comment by facultymatt** [comment]
Ok, seems to be working now: 
https://github.com/facultymatt/genesis-skeleton/commit/5501a0821560b2b28f109bdcf961d94c299349fd

**Comment by ericclemmons** [comment]
Sweet!

I'll pull together both (cherry-pick, of course, so you get credit!) and create a PR for approval.

> https://github.com/facultymatt/genesis-skeleton/commit/707609d408d235083a8093abe311009610e57ee4 
> https://github.com/facultymatt/genesis-skeleton/commit/5501a0821560b2b28f109bdcf961d94c299349fd

@kwhitley & I were discussing (since this project is the basis for a _large_ project at our company) the line we're drawing between Express & Angular with this, and it seems to be the following:

> Express powers the API & communication to the DB and other services and any errors therein.  Angular, however, is responsible for the entire front-end navigation & experience, including errors within the application itself.

**Comment by ericclemmons** [comment]
@facultymatt Man, this sucks.  The problem is, HTML5 history is not supported by IE8 & IE9, which constitutes a large chunk of users.  Supporting both HTML5 & hashes means that URLs will have to be dynamic, and that either means:
1. All URLs have to have a `{{ hashPrefix }}` variable, which is messy and relies on globals or
2. All URLs use a dynamic URL generator, like `ng-route`, or `ng-href` (if the former existed or the latter supported HTML5 history)

Because there isn't a clean way or a consensus on how the community solves this problem, I'm going to opt to default to supporting only the angular default of `$location.html5Mode(false)` until a better solution is available.  (I have one in mind :D).

Don't worry, I will be cherry-picking in your commits to that PR so your work isn't lost @facultymatt!
