### ISSUE TITLE
Watch fails on lint/jshint errors

### ISSUE THREAD

**Issue by kwhitley** [ericclemmons/genesis-skeleton#72]
Would be awesome if the error was shown and the build process terminated (leaving the existing server instance intact).

**Comment by ericclemmons** [comment]
I looked into this quite a bit, and it _would_ be possible via `regarde`'s `spawn` option **if** `jshint` was ran _alone_ rather than alongside `express-server` (which has to be ran within the same process each time).

Anyway, simple solution is: `grunt server --force`.  This will force continuation of tasks rather than exiting.

Works great (as long as you're not having the EADDRINUSE errors)!
