### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by psyllos** [ericclemmons/genesis-skeleton#89]
It seems that the live reload does not work into the browser : the live reload script is not injected into the page

**Comment by ericclemmons** [comment]
That's correct.

We personally use the Chrome Extension (https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en) (there's one for Firefox & others) because of a known issue with Express's `compress` middleware that does not recalculate the `content-length` when another middleware injects the script automatically.

If this is a "must have" for you, I can look into implementation again to see if the issue has been resolved.

**Comment by psyllos** [comment]
No,it's a "nice to have". I was using the extension and it's ok. Thank you.
